<a href="https://colab.research.google.com/github/AndreesArgueta/etl-data-pipeline25-0389-2022/blob/main/etl_A_notas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/AndreesArgueta/etl-data-pipeline25-0389-2022/refs/heads/main/data/raw/A_notas.csv"

df = pd.read_csv(url)

df.head()

  id_nota id_estudiante id_curso nota  periodo
0   N5000         E1102     C204  7.9   I-2025
1   N5001         E1179     C205  8.1   I-2025
2   N5002         E1092     C202  8.6   I-2025
3   N5003         E1014     C211  8.0   I-2025
4   N5004         E1106     C208  7.4  II-2025

LIMPIEZA DE DATOS

In [3]:
notas = df.copy()

# Normalizar nombres de columnas (eliminar espacios extra)
notas.columns = notas.columns.str.strip().str.lower()

# Limpiar espacios en columnas de texto
for col in notas.select_dtypes(include="object").columns:
    notas[col] = notas[col].astype(str).str.strip()

# Convertir vacíos a NA
notas = notas.replace(r'^\s*$', pd.NA, regex=True)

# Asegurarse de que la columna 'nota' sea numérica y manejar valores incorrectos
notas['nota'] = pd.to_numeric(notas['nota'], errors='coerce')

# Validar que las notas sean entre 0 y 10 (típico en sistemas de calificación)
notas['nota'] = notas['nota'].apply(lambda x: x if 0 <= x <= 10 else pd.NA)

# Limpiar la columna 'periodo' (comprobar que no tenga espacios extras)
notas['periodo'] = notas['periodo'].str.strip()

# Eliminar duplicados
notas = notas.drop_duplicates()

SEPARAR DATOS VALIDOS Y RECHAZADOS

In [4]:
validos = notas[
    notas['id_nota'].notna() &
    notas['id_estudiante'].notna() &
    notas['id_curso'].notna() &
    notas['nota'].notna() &
    notas['periodo'].notna()
].copy()

rechazados = notas[
    notas['id_nota'].isna() |
    notas['id_estudiante'].isna() |
    notas['id_curso'].isna() |
    notas['nota'].isna() |
    notas['periodo'].isna()
].copy()

MOTIVO DE RECHAZO

In [6]:
def motivo(row):

    motivos = []

    if pd.isna(row['id_nota']):
        motivos.append("id_nota_vacio")

    if pd.isna(row['id_estudiante']):
        motivos.append("id_estudiante_vacio")

    if pd.isna(row['id_curso']):
        motivos.append("id_curso_vacio")

    if pd.isna(row['nota']):
        motivos.append("nota_vacia")

    if pd.isna(row['periodo']):
        motivos.append("periodo_vacio")

    if not pd.isna(row['nota']) and (row['nota'] < 0 or row['nota'] > 10):
        motivos.append("nota_fuera_de_rango")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

EXPORTAR ARCHIVOS

In [7]:
validos.to_csv("notas_curated.csv", index=False)
rechazados.to_csv("notas_rejects.csv", index=False)

CONECTAR CON POSTRESQL

In [8]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_argueta:RuSM0PkNryjJpjcJs9z3LwZNjP3Iuoph@dpg-d6qu6ivgi27c73aaaar0-a.oregon-postgres.render.com/etl_seguros_c75s"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 38.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

CARGAR DATOS EN POSTGRESQL

In [9]:
validos.to_sql(
    'notas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'notas_rejects',
    engine,
    if_exists='append',
    index=False
)

27

VALIDAR LA CARGA

In [11]:
pd.read_sql(
"SELECT * FROM notas_curated LIMIT 10",
engine)

  id_nota id_estudiante id_curso  nota  periodo
0   N5000         E1102     C204   7.9   I-2025
1   N5001         E1179     C205   8.1   I-2025
2   N5002         E1092     C202   8.6   I-2025
3   N5003         E1014     C211   8.0   I-2025
4   N5004         E1106     C208   7.4  II-2025
5   N5005         E1071     C204   3.9  II-2025
6   N5006         E1020     C207   5.2  II-2025
7   N5007         E1102     C200   5.8   I-2025
8   N5008         E1121     C204   2.7   I-2025
9   N5009         E1074     C202   6.2   I-2025